from typing import Any, Iterable

class Data:
    def size(self) -> int: ...
    def type(self) -> Any: ...
    def get_value(self, index: int) -> Any: ...
    def __getitem__(self, index: int) -> Any: ...

class _VectorDataForTest(Data):
    def __init__(self, values: Iterable[Any]) -> None: ...
