from typing import Any, Iterable

class Data:
    def size(self) -> int: ...
    def type(self) -> Any: ...
    def get_value(self, index: int) -> Any: ...
    def set_value(self, index: int, value: Any) -> None: ...
    def new_like(self, values: Iterable[Any], *, mutable: bool = True) -> Data: ...
    def scatter(
        self,
        to_scatter: Any,
        scatter_onto: Any,
        mapping: Any,
        mapping_offset: int = 0,
    ) -> None: ...
    def is_evictable(self) -> bool: ...
    def is_mutable(self) -> bool: ...
    def dlpack_info(self) -> dict[str, int]: ...
    def is_evicted(self) -> bool: ...
    def evict(self) -> None: ...
    def promote(self) -> None: ...
    def is_released(self) -> bool: ...
    def release(self) -> None: ...
    @staticmethod
    def dispatch_op(operation_name: str) -> Any: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...

class _VectorDataForTest(Data):
    def __init__(self, values: Iterable[Any]) -> None: ...

class CPU(Data):
    def __init__(
        self,
        size: int,
        pointer: int | None = None,
        *,
        mutable: bool = True,
        dtype: Any = None,
    ) -> None: ...
    def pointer(self) -> int: ...
    def dlpack_info(self) -> dict[str, int]: ...
    def set_value(self, index: int, value: Any) -> None: ...
    def new_like(
        self,
        values: Iterable[Any],
        *,
        mutable: bool = True,
        dtype: Any = None,
    ) -> CPU: ...
    def scatter(
        self,
        to_scatter: Any,
        scatter_onto: Any,
        mapping: Any,
        mapping_offset: int = 0,
    ) -> None: ...
    @staticmethod
    def dispatch_op(operation_name: str) -> Any: ...

class _CPUAddOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUScalarMulOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUElementwiseMulOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUDivOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUExpOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUReLUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUSigmoidOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUTanhOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUGELUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUSiLUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUSoftplusOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUELUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPULeakyReLUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUPowOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUReduceSumOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUMatmulOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...
