from typing import Any, Iterable

class Data:
    def size(self) -> int: ...
    def type(self) -> Any: ...
    def get_value(self, index: int) -> Any: ...
    def set_value(self, index: int, value: Any) -> None: ...
    def is_evictable(self) -> bool: ...
    def is_mutable(self) -> bool: ...
    def is_evicted(self) -> bool: ...
    def evict(self) -> None: ...
    def promote(self) -> None: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...

class _VectorDataForTest(Data):
    def __init__(self, values: Iterable[Any]) -> None: ...
