from collections.abc import Callable
from typing import Any

def lex(command: str, token_type: type[Any]) -> list[Any]: ...
def _cached_rearrange_spec(command: str, compiler: Callable[[str], Any]) -> Any: ...
def _cached_reduce_spec(command: str, compiler: Callable[[str], Any]) -> Any: ...
def _cached_einsum_spec(command: str, compiler: Callable[[str], Any]) -> Any: ...
