from typing import Any

from .layout import Layout

class _LayoutCache:
    def __init__(self, layout: Layout) -> None: ...
    @property
    def logical_size(self) -> int: ...
    @property
    def cosize(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def leaf_rank(self) -> int: ...
    @property
    def leaf_shapes(self) -> list[int]: ...
    @property
    def leaf_strides(self) -> list[int]: ...
    def expand_key(self, key: int) -> list[int]: ...
    def index_expanded(self, key: list[int]) -> int: ...
    def increment_key(self, key: list[int]) -> list[int]: ...
    def increment_mode(self, key: list[int], mode: int) -> list[int]: ...
    def get_index(self, key: Any) -> int: ...

def get_index(layout: Layout, key: Any) -> int: ...
