from typing import Any

def is_grad_enabled() -> bool: ...
def set_grad_enabled(enabled: bool) -> None: ...

class Operation:
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def forward(self, *inputs: Any) -> Any: ...
    def _forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    def store_inputs(self, *inputs: Any) -> None: ...
    def inputs(self) -> tuple[Any, ...]: ...
