from typing import Any

class Operation:
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def forward(self, *inputs: Any) -> Any: ...
    def _forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    def store_inputs(self, *inputs: Any) -> None: ...
    def inputs(self) -> tuple[Any, ...]: ...
