from typing import Any

from .data import Data
from .layout import Layout

class Tensor:
    def __init__(self, data: Data, offset: int, layout: Layout) -> None: ...
    @property
    def data(self) -> Data: ...
    @property
    def offset(self) -> int: ...
    @property
    def layout(self) -> Layout: ...
    @property
    def autograd_ctx(self) -> Any | None: ...
    @autograd_ctx.setter
    def autograd_ctx(self, autograd_ctx: Any | None) -> None: ...
    @property
    def grad(self) -> Tensor | None: ...
    @grad.setter
    def grad(self, grad: Tensor | None) -> None: ...
    def retain_grad(self, retain: bool = True) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __add__(self, other: Any) -> Tensor: ...
    def __mul__(self, other: Any) -> Tensor: ...
    def __rmul__(self, other: Any) -> Tensor: ...
    def __truediv__(self, other: Any) -> Tensor: ...
    def __pow__(self, exponent: Any) -> Tensor: ...
    def __matmul__(self, other: Any) -> Tensor: ...
    def size(self) -> int: ...
    def is_mutable(self) -> bool: ...
    def is_evictable(self) -> bool: ...
    def is_evicted(self) -> bool: ...
    def evict(self) -> None: ...
    def promote(self) -> None: ...
    def dtype(self) -> Any: ...
    def is_differentiable(self) -> bool: ...
    def device(self) -> type[Any]: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(
        self,
        stream: Any = None,
        *,
        max_version: tuple[int, int] | None = None,
        dl_device: tuple[int, int] | None = None,
        copy: bool | None = None,
    ) -> Any: ...
    def backward(self, gradient: Tensor | None = None) -> None: ...
    @staticmethod
    def backwards_traversal(gradient: Tensor, operation: Any | None) -> None: ...
