from typing import Any

from .data import Data
from .layout import Layout

class Tensor:
    def __init__(self, data: Data, offset: int, layout: Layout) -> None: ...
    @property
    def data(self) -> Data: ...
    @property
    def offset(self) -> int: ...
    @property
    def layout(self) -> Layout: ...
    def __getitem__(self, key: Any) -> Any: ...
    def size(self) -> int: ...
    def dtype(self) -> Any: ...
    def device(self) -> type[Any]: ...
