from collections.abc import Iterable
from enum import Enum
from os import PathLike
from typing import Any

from ._data import Data as Data

class DataType(Enum):
    Any = "Any"

class Generic(Data):
    def __init__(self, values: Iterable[Any]) -> None: ...
    def size(self) -> int: ...
    def type(self) -> DataType: ...
    def get_value(self, index: int) -> Any: ...

class GenericEvictable(Generic):
    def __init__(self, values: Iterable[Any], path: str | PathLike[str]) -> None: ...
    def size(self) -> int: ...
    def is_evictable(self) -> bool: ...
