from typing import Any

from ._tensor import Tensor
from .data import Data
from .layout import Layout

class Parameter(Tensor):
    def __init__(
        self,
        tensor_or_data: Tensor | Data,
        offset: int | None = None,
        layout: Layout | None = None,
        *,
        name: str | None = None,
    ) -> None: ...
    name: str | None

class Module:
    name: str | None
    def __init__(self, *, name: str | None = None) -> None: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def modules(self) -> tuple[Module, ...]: ...
    def parameters(self) -> tuple[Parameter, ...]: ...
    def get_named_parameters(self) -> tuple[tuple[str, Parameter], ...]: ...
