from contextlib import AbstractContextManager
from typing import Any

from ._operation import Operation as Operation
from .layout import Tree
from .tensor import Tensor

class GenericAddOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericScalarMulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericElementwiseMulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericDivOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericExpOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericPowOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericReduceSumOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericMatmulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericViewOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class RearrangeOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class PermuteOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

def is_grad_enabled() -> bool: ...
def set_grad_enabled(enabled: bool) -> None: ...
def no_grad() -> AbstractContextManager[None]: ...
def add(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def elementwise_mul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def mul(tensor: Tensor, scalar: Any) -> Tensor: ...
def div(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def exp(tensor: Tensor) -> Tensor: ...
def pow(tensor: Tensor, exponent: Any) -> Tensor: ...
def reduce(tensor: Tensor) -> Tensor: ...
def matmul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def rearrange(
    tensor: Tensor, output: Tree, selection: Tree | None = None
) -> Tensor: ...
def permute(tensor: Tensor, *order: Any) -> Tensor: ...
def view(tensor: Tensor, key: Any) -> Tensor: ...
