"""Autograd operation classes and public tensor operation functions.

The implementation is split across three private modules: shared helpers in
``_operation_helpers``, Generic (Python-backed) operation classes in
``_generic_ops``, and the public dispatch functions in ``_functional``. This
module re-exports the public surface.
"""

from __future__ import annotations

from ._functional import (
    add,
    div,
    einsum,
    elementwise_mul,
    elu,
    exp,
    gelu,
    is_grad_enabled,
    leaky_relu,
    matmul,
    mul,
    no_grad,
    permute,
    pow,
    rearrange,
    reduce,
    relu,
    set_grad_enabled,
    sigmoid,
    silu,
    softplus,
    tanh,
    view,
)
from ._generic_ops import (
    GenericAddOperation,
    GenericDivOperation,
    GenericElementwiseMulOperation,
    GenericELUOperation,
    GenericExpOperation,
    GenericGELUOperation,
    GenericLeakyReLUOperation,
    GenericMatmulOperation,
    GenericPowOperation,
    GenericReduceSumOperation,
    GenericReLUOperation,
    GenericScalarMulOperation,
    GenericSigmoidOperation,
    GenericSiLUOperation,
    GenericSoftplusOperation,
    GenericTanhOperation,
    GenericViewOperation,
    PermuteOperation,
    RearrangeOperation,
)
from ._operation_helpers import Operation

__all__ = [
    "GenericAddOperation",
    "GenericDivOperation",
    "GenericELUOperation",
    "GenericElementwiseMulOperation",
    "GenericExpOperation",
    "GenericGELUOperation",
    "GenericLeakyReLUOperation",
    "GenericMatmulOperation",
    "GenericPowOperation",
    "GenericReLUOperation",
    "GenericReduceSumOperation",
    "GenericScalarMulOperation",
    "GenericSiLUOperation",
    "GenericSigmoidOperation",
    "GenericSoftplusOperation",
    "GenericTanhOperation",
    "GenericViewOperation",
    "Operation",
    "PermuteOperation",
    "RearrangeOperation",
    "add",
    "div",
    "einsum",
    "elementwise_mul",
    "elu",
    "exp",
    "gelu",
    "is_grad_enabled",
    "leaky_relu",
    "matmul",
    "mul",
    "no_grad",
    "permute",
    "pow",
    "rearrange",
    "reduce",
    "relu",
    "set_grad_enabled",
    "sigmoid",
    "silu",
    "softplus",
    "tanh",
    "view",
]
