from collections.abc import Iterable
from typing import Any

from ..base import Carrier
from ..dtype import DType

class Evictable(Carrier):
    def __init__(self, primary: Carrier, secondary: Carrier) -> None: ...
    @property
    def primary(self) -> Carrier: ...
    @property
    def secondary(self) -> Carrier: ...
    def size(self) -> int: ...
    def dtype(self) -> DType: ...
    def is_mutable(self) -> bool: ...
    def _is_mutable(self) -> bool: ...
    def is_evicted(self) -> bool: ...
    def get_value(self, index: int) -> Any: ...
    def set_value(self, index: int, value: Any) -> None: ...
    def new_like(
        self,
        values: Iterable[Any],
        *,
        mutable: bool = True,
        dtype: DType | None = None,
    ) -> Evictable: ...
    def allocate_like(
        self,
        size: int,
        *,
        mutable: bool = True,
        dtype: DType | None = None,
        empty: bool = False,
    ) -> Evictable: ...
    def evict(self) -> None: ...
    def promote(self) -> None: ...
    def scatter(
        self,
        to_scatter: Any,
        scatter_onto: Any,
        mapping: Any,
        mapping_offset: int = 0,
    ) -> None: ...
    def dlpack_info(self) -> dict[str, int]: ...
    def _require_promoted(self) -> Carrier: ...
    def _wrap_primary(self, primary: Carrier) -> Evictable: ...
    def dispatch_op(self, operation_name: str) -> Any: ...
