"""Staged kernel verification, provenance reports, and evidence models."""

from .api import test_backend
from .classification import (
    MOVEMENT_CLASSIFICATIONS,
    classifications_for_kernel,
    classify_cpu_kernel_plans,
    native_cpu_kernel_manifest,
    require_complete_classification,
)
from .comparison import (
    Comparison,
    compare_float32,
    float32_bits,
    float32_ulp_distance,
    gamma_bound,
)
from .model import (
    CaseDescriptor,
    ClassificationDisposition,
    Deviations,
    EvidenceRecord,
    KernelDescriptor,
    KernelPlanDescriptor,
    OracleCertificate,
    PlanKey,
    ReportHeader,
    Tolerance,
    VerificationClass,
    VerificationOutcome,
    VerificationReport,
    VerificationStage,
    VerificationSummary,
)
from .payloads import (
    AnalyticCase,
    EncodedFloat32Payload,
    EncodedInputs,
    EncodedInt32Payload,
    ExactStructuralPayload,
    adversarial_float32_payload,
    analytic_cases,
    arbitrary_float32_payload,
    exact_structural_payload,
    wide_exponent_float32_payload,
)
from .provenance import (
    CompilationInput,
    CompilationManifest,
    CompilationReceipt,
    CompilationTarget,
    CompilationToolchain,
    load_compilation_manifest,
)
from .stage_one import StageOneResult, run_stage_one

__all__ = [
    "MOVEMENT_CLASSIFICATIONS",
    "AnalyticCase",
    "CaseDescriptor",
    "ClassificationDisposition",
    "Comparison",
    "CompilationInput",
    "CompilationManifest",
    "CompilationReceipt",
    "CompilationTarget",
    "CompilationToolchain",
    "Deviations",
    "EncodedFloat32Payload",
    "EncodedInputs",
    "EncodedInt32Payload",
    "EvidenceRecord",
    "ExactStructuralPayload",
    "KernelDescriptor",
    "KernelPlanDescriptor",
    "OracleCertificate",
    "PlanKey",
    "ReportHeader",
    "StageOneResult",
    "Tolerance",
    "VerificationClass",
    "VerificationOutcome",
    "VerificationReport",
    "VerificationStage",
    "VerificationSummary",
    "adversarial_float32_payload",
    "analytic_cases",
    "arbitrary_float32_payload",
    "classifications_for_kernel",
    "classify_cpu_kernel_plans",
    "compare_float32",
    "exact_structural_payload",
    "float32_bits",
    "float32_ulp_distance",
    "gamma_bound",
    "load_compilation_manifest",
    "native_cpu_kernel_manifest",
    "require_complete_classification",
    "run_stage_one",
    "test_backend",
    "wide_exponent_float32_payload",
]
