from collections.abc import Iterable

class _TransferResult:
    @property
    def status(self) -> str: ...
    @property
    def completed_bytes(self) -> int: ...
    @property
    def error_number(self) -> int: ...
    @property
    def is_complete(self) -> bool: ...

class _CloseResult:
    @property
    def error_number(self) -> int: ...
    @property
    def succeeded(self) -> bool: ...

class _BlockDeviceHandle:
    @property
    def capacity_bytes(self) -> int: ...
    @property
    def logical_block_size(self) -> int: ...
    @property
    def physical_block_size(self) -> int: ...
    def is_open(self) -> bool: ...
    def read_into(
        self, destination_pointer: int, byte_offset: int, byte_count: int
    ) -> _TransferResult: ...
    def write_from(
        self, source_pointer: int, byte_offset: int, byte_count: int
    ) -> _TransferResult: ...
    def read_bytes(
        self, byte_offset: int, byte_count: int
    ) -> tuple[_TransferResult, bytes]: ...
    def write_bytes(self, byte_offset: int, values: bytes) -> _TransferResult: ...
    def zero_fill(self, byte_offset: int, byte_count: int) -> _TransferResult: ...
    def close(self) -> _CloseResult: ...

class _TestIoState:
    def __init__(
        self,
        *,
        read_script: Iterable[tuple[str, int]] = (),
        write_script: Iterable[tuple[str, int]] = (),
        close_error: int = 0,
    ) -> None: ...
    @property
    def read_attempts(self) -> int: ...
    @property
    def write_attempts(self) -> int: ...
    @property
    def close_attempts(self) -> int: ...
    @property
    def opened_descriptor(self) -> int: ...
    @property
    def last_closed_descriptor(self) -> int: ...
    @property
    def descriptor_was_closed(self) -> bool: ...
    @property
    def read_steps_remaining(self) -> int: ...
    @property
    def write_steps_remaining(self) -> int: ...

def _open_block_device(path: str) -> _BlockDeviceHandle: ...
def _open_block_device_for_test(
    path: str,
    capacity_bytes: int,
    logical_block_size: int,
    physical_block_size: int,
    io: _TestIoState,
) -> _BlockDeviceHandle: ...
