from collections.abc import Iterable
from typing import Any, final

from .carriers.dtype import DType
from .carriers.operation_capability import OperationCapability
from .carriers.operation_policy import OperationPlan

class Carrier:
    def size(self) -> int: ...
    def dtype(self) -> Any: ...
    def supports_storage_dtype(self, dtype: DType) -> bool: ...
    def get_value(self, index: int) -> Any: ...
    def set_value(self, index: int, value: Any) -> None: ...
    def new_like(self, values: Iterable[Any], *, mutable: bool = True) -> Carrier: ...
    def allocate_like(
        self,
        size: int,
        *,
        mutable: bool = True,
        dtype: Any = None,
        empty: bool = False,
    ) -> Carrier: ...
    def scatter(
        self,
        to_scatter: Any,
        scatter_onto: Any,
        mapping: Any,
        mapping_offset: int = 0,
    ) -> None: ...
    def is_mutable(self) -> bool: ...
    def is_owned(self) -> bool: ...
    def _has_owner_access(self) -> bool: ...
    def _is_mutable(self) -> bool: ...
    def _supports_storage_dtype(self, dtype: DType) -> bool: ...
    def _claim_ownership(self) -> int: ...
    def _relinquish_ownership(self, token: int) -> None: ...
    def _begin_owner_access(self, token: int) -> None: ...
    def _end_owner_access(self, token: int) -> None: ...
    def dlpack_info(self) -> dict[str, int]: ...
    @property
    def version(self) -> int: ...
    def _increment_version(self) -> None: ...
    def is_released(self) -> bool: ...
    def release(self) -> None: ...
    def dispatch_op(self, operation_name: str) -> Any: ...
    def operation_capabilities(
        self, operation_name: str | None = None
    ) -> tuple[OperationCapability, ...]: ...
    def supports_operation_plan(self, plan: OperationPlan) -> bool: ...
    def unsupported_plan_reason(self, plan: OperationPlan) -> str | None: ...
    def require_operation_plan(self, plan: OperationPlan) -> OperationCapability: ...
    def _dispatch_op(self, operation_name: str) -> Any: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...

class _VectorCarrierForTest(Carrier):
    def __init__(self, values: Iterable[Any]) -> None: ...

@final
class CPU(Carrier):
    def __init__(
        self,
        size: int,
        pointer: int | None = None,
        *,
        mutable: bool = True,
        dtype: Any = None,
        empty: bool = False,
    ) -> None: ...
    def _dispatch_op(self, operation_name: str) -> Any: ...
    def pointer(self) -> int: ...
    def dlpack_info(self) -> dict[str, int]: ...
    def set_value(self, index: int, value: Any) -> None: ...
    def new_like(
        self,
        values: Iterable[Any],
        *,
        mutable: bool = True,
        dtype: Any = None,
    ) -> CPU: ...
    def allocate_like(
        self,
        size: int,
        *,
        mutable: bool = True,
        dtype: Any = None,
        empty: bool = False,
    ) -> CPU: ...
    def scatter(
        self,
        to_scatter: Any,
        scatter_onto: Any,
        mapping: Any,
        mapping_offset: int = 0,
    ) -> None: ...

class _CPUAddOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUScalarMulOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUElementwiseMulOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUDivOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUExpOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUReLUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUSigmoidOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUTanhOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUGELUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUSiLUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUSoftplusOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUELUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPULeakyReLUOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUPowOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUReduceSumOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...

class _CPUMatmulOperation:
    def forward(self, *inputs: Any) -> Any: ...
    def backward(self, gradient: Any) -> Any: ...
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def inputs(self) -> tuple[Any, ...]: ...
