from typing import Any

def is_grad_enabled() -> bool: ...
def set_grad_enabled(enabled: bool) -> None: ...

class _RawProfilerEvent:
    @property
    def id(self) -> int: ...
    @property
    def parent_id(self) -> int | None: ...
    @property
    def name(self) -> str: ...
    @property
    def carrier_type(self) -> type[Any]: ...
    @property
    def implementation_type(self) -> type[Any]: ...
    @property
    def input_shapes(self) -> tuple[Any, ...] | None: ...
    @property
    def start_time_ns(self) -> int: ...
    @property
    def duration_ns(self) -> int: ...
    @property
    def self_time_ns(self) -> int: ...
    @property
    def thread_id(self) -> int: ...
    @property
    def succeeded(self) -> bool: ...

class _RawProfilerSession:
    def __init__(
        self,
        carrier_types: object | None = None,
        record_shapes: bool = False,
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def _abandon(self) -> None: ...
    def events(self) -> tuple[_RawProfilerEvent, ...]: ...
    @property
    def is_active(self) -> bool: ...

class Operation:
    @property
    def ctx(self) -> dict[Any, Any]: ...
    def forward(self, *inputs: Any) -> Any: ...
    def _forward(self, *inputs: Any) -> Any: ...
    def _execute_lowered(self, *inputs: Any) -> Any: ...
    @property
    def _operation_name(self) -> str | None: ...
    @property
    def _dispatch_carrier_class(self) -> type[Any] | None: ...
    def backward(self, gradient: Any) -> Any: ...
    def store_inputs(self, *inputs: Any) -> None: ...
    def inputs(self) -> tuple[Any, ...]: ...
    def input_versions(self) -> tuple[int, ...]: ...
    def validate_input_versions(self) -> None: ...

def _execute_lowered(operation: Operation, *inputs: Any) -> Any: ...
