from collections.abc import Iterable
from contextlib import AbstractContextManager
from typing import Any, Literal, NamedTuple, Self, overload

from ._operation import Operation as Operation
from .carriers import Carrier, SimpleDType
from .layout import Shape, Stride, Tree
from .tensor import Tensor

__all__ = [
    "BroadcastOperation",
    "CpuToFileBackedMoveOperation",
    "ElementwiseMoveOperation",
    "EvictableOperation",
    "FileBackedToCpuMoveOperation",
    "GenericAbsOperation",
    "GenericAddOperation",
    "GenericArgMaxOperation",
    "GenericArgMinOperation",
    "GenericAsStridedOperation",
    "GenericCeilOperation",
    "GenericClampOperation",
    "GenericConvGeneralOperation",
    "GenericCosOperation",
    "GenericCumsumOperation",
    "GenericDivOperation",
    "GenericELUOperation",
    "GenericElementwiseMulOperation",
    "GenericEqOperation",
    "GenericErfOperation",
    "GenericExp2Operation",
    "GenericExpOperation",
    "GenericFloorOperation",
    "GenericGELUOperation",
    "GenericGatherOperation",
    "GenericLeOperation",
    "GenericLeakyReLUOperation",
    "GenericLog2Operation",
    "GenericLogOperation",
    "GenericLogicalNotOperation",
    "GenericLtOperation",
    "GenericMatmulOperation",
    "GenericMaximumOperation",
    "GenericMinimumOperation",
    "GenericNeOperation",
    "GenericNegOperation",
    "GenericPowOperation",
    "GenericReLUOperation",
    "GenericRecipOperation",
    "GenericReduceMaxOperation",
    "GenericReduceMinOperation",
    "GenericReduceProdOperation",
    "GenericReduceSumOperation",
    "GenericRemOperation",
    "GenericRoundOperation",
    "GenericRsqrtOperation",
    "GenericScalarMulOperation",
    "GenericScatterAddOperation",
    "GenericScatterOperation",
    "GenericSelectOperation",
    "GenericSiLUOperation",
    "GenericSigmoidOperation",
    "GenericSignOperation",
    "GenericSinOperation",
    "GenericSoftplusOperation",
    "GenericSortIndicesOperation",
    "GenericSortValuesOperation",
    "GenericSqrtOperation",
    "GenericSubOperation",
    "GenericTanhOperation",
    "GenericTopKIndicesOperation",
    "GenericTopKValuesOperation",
    "GenericViewOperation",
    "MoveOperation",
    "Operation",
    "PermuteOperation",
    "Profiler",
    "ProfilerAggregate",
    "ProfilerEvent",
    "RearrangeOperation",
    "ReshapeOperation",
    "SortResult",
    "SqueezeOperation",
    "TopKResult",
    "UnsqueezeOperation",
    "abs",
    "add",
    "argmax",
    "argmin",
    "as_strided",
    "broadcast_in_dim",
    "broadcast_to",
    "ceil",
    "clamp",
    "conv_general",
    "cos",
    "cumsum",
    "div",
    "einsum",
    "elementwise_mul",
    "elu",
    "eq",
    "erf",
    "exp",
    "exp2",
    "floor",
    "gather",
    "ge",
    "gelu",
    "gt",
    "is_grad_enabled",
    "le",
    "leaky_relu",
    "log",
    "log2",
    "logical_not",
    "lt",
    "matmul",
    "maximum",
    "minimum",
    "move",
    "mul",
    "ne",
    "neg",
    "no_grad",
    "permute",
    "pow",
    "profile",
    "rearrange",
    "recip",
    "reduce_max",
    "reduce_min",
    "reduce_prod",
    "reduce_sum",
    "relu",
    "rem",
    "reshape",
    "round",
    "rsqrt",
    "scatter",
    "scatter_add",
    "select",
    "set_grad_enabled",
    "sigmoid",
    "sign",
    "silu",
    "sin",
    "softplus",
    "sort",
    "sqrt",
    "squeeze",
    "sub",
    "tanh",
    "topk",
    "unsqueeze",
]

class BroadcastOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class SqueezeOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class UnsqueezeOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericAbsOperation(Operation): ...
class GenericArgMaxOperation(Operation): ...
class GenericArgMinOperation(Operation): ...
class GenericAsStridedOperation(Operation): ...
class GenericCeilOperation(Operation): ...
class GenericClampOperation(Operation): ...
class GenericConvGeneralOperation(Operation): ...
class GenericCosOperation(Operation): ...
class GenericCumsumOperation(Operation): ...
class GenericEqOperation(Operation): ...
class GenericErfOperation(Operation): ...
class GenericExp2Operation(Operation): ...
class GenericFloorOperation(Operation): ...
class GenericGatherOperation(Operation): ...
class GenericLeOperation(Operation): ...
class GenericLogicalNotOperation(Operation): ...
class GenericLogOperation(Operation): ...
class GenericLog2Operation(Operation): ...
class GenericLtOperation(Operation): ...
class GenericMaximumOperation(Operation): ...
class GenericMinimumOperation(Operation): ...
class GenericNegOperation(Operation): ...
class GenericNeOperation(Operation): ...
class GenericRecipOperation(Operation): ...
class GenericReduceMaxOperation(Operation): ...
class GenericReduceMinOperation(Operation): ...
class GenericReduceProdOperation(Operation): ...
class GenericRemOperation(Operation): ...
class GenericRoundOperation(Operation): ...
class GenericRsqrtOperation(Operation): ...
class GenericScatterAddOperation(Operation): ...
class GenericScatterOperation(Operation): ...
class GenericSelectOperation(Operation): ...
class GenericSignOperation(Operation): ...
class GenericSinOperation(Operation): ...
class GenericSortIndicesOperation(Operation): ...
class GenericSortValuesOperation(Operation): ...
class GenericSqrtOperation(Operation): ...
class GenericTopKIndicesOperation(Operation): ...
class GenericTopKValuesOperation(Operation): ...
class ReshapeOperation(Operation): ...

class GenericAddOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericSubOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericScalarMulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericElementwiseMulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericDivOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericExpOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericReLUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericSigmoidOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericTanhOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericGELUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericSiLUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericSoftplusOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericELUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericLeakyReLUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericPowOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericReduceSumOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericMatmulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericViewOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class RearrangeOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class PermuteOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class MoveOperation(Operation):
    source_class: type | None
    destination_class: type | None
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...
    def _copy(
        self, tensor: Tensor, destination: Any, output: Tensor, element_count: int
    ) -> None: ...

class ElementwiseMoveOperation(MoveOperation): ...
class CpuToFileBackedMoveOperation(MoveOperation): ...
class FileBackedToCpuMoveOperation(MoveOperation): ...

class EvictableOperation(Operation):
    def __init__(self, primary_operation: Operation) -> None: ...
    @property
    def primary_operation(self) -> Operation: ...
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any, options: Any | None = None) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor | None, ...]: ...

type ShapeSnapshot = tuple[int | ShapeSnapshot, ...]
type InputShapes = tuple[ShapeSnapshot | None, ...]

class ProfilerEvent:
    def __init__(
        self,
        id: int,
        parent_id: int | None,
        name: str,
        carrier_type: type[Carrier],
        implementation_type: type[Any],
        input_shapes: InputShapes | None,
        start_time_ns: int,
        duration_ns: int,
        self_time_ns: int,
        thread_id: int,
        succeeded: bool,
    ) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def parent_id(self) -> int | None: ...
    @property
    def name(self) -> str: ...
    @property
    def carrier_type(self) -> type[Carrier]: ...
    @property
    def implementation_type(self) -> type[Any]: ...
    @property
    def input_shapes(self) -> InputShapes | None: ...
    @property
    def start_time_ns(self) -> int: ...
    @property
    def duration_ns(self) -> int: ...
    @property
    def self_time_ns(self) -> int: ...
    @property
    def thread_id(self) -> int: ...
    @property
    def succeeded(self) -> bool: ...

class ProfilerAggregate:
    def __init__(
        self,
        name: str,
        carrier_type: type[Carrier],
        input_shapes: InputShapes | None,
        count: int,
        total_time_ns: int,
        self_total_time_ns: int,
        mean_time_ns: float,
        min_time_ns: int,
        max_time_ns: int,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def carrier_type(self) -> type[Carrier]: ...
    @property
    def input_shapes(self) -> InputShapes | None: ...
    @property
    def count(self) -> int: ...
    @property
    def total_time_ns(self) -> int: ...
    @property
    def self_total_time_ns(self) -> int: ...
    @property
    def mean_time_ns(self) -> float: ...
    @property
    def min_time_ns(self) -> int: ...
    @property
    def max_time_ns(self) -> int: ...

class Profiler(AbstractContextManager[Profiler]):
    def __init__(
        self,
        *,
        carriers: Iterable[type[Carrier]] | None = None,
        record_shapes: bool = False,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> Literal[False]: ...
    def events(self) -> tuple[ProfilerEvent, ...]: ...
    def key_averages(
        self, *, group_by_input_shape: bool = False
    ) -> tuple[ProfilerAggregate, ...]: ...
    def table(
        self,
        *,
        sort_by: str = "self_total_time_ns",
        descending: bool = True,
        group_by_input_shape: bool = False,
        row_limit: int | None = None,
    ) -> str: ...

def is_grad_enabled() -> bool: ...
def set_grad_enabled(enabled: bool) -> None: ...
def no_grad() -> AbstractContextManager[None]: ...
def add(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def abs(tensor: Tensor) -> Tensor: ...
def argmax(tensor: Tensor, description: str) -> Tensor: ...
def argmin(tensor: Tensor, description: str) -> Tensor: ...
def as_strided(tensor: Tensor, shape: Shape, stride: Stride) -> Tensor: ...
def broadcast_to(tensor: Tensor, target: Shape) -> Tensor: ...
def ceil(tensor: Tensor) -> Tensor: ...
@overload
def clamp(tensor: Tensor, lower: Tensor, upper: Tensor) -> Tensor: ...
@overload
def clamp(tensor: Tensor, lower: Tensor, upper: Any) -> Tensor: ...
@overload
def clamp(tensor: Tensor, lower: Any, upper: Tensor) -> Tensor: ...
@overload
def clamp(tensor: Tensor, lower: Any, upper: Any) -> Tensor: ...
def cos(tensor: Tensor) -> Tensor: ...
def broadcast_in_dim(
    tensor: Tensor, target: Shape, broadcast_dimensions: Iterable[Any]
) -> Tensor: ...
def sub(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def elementwise_mul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def div(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def eq(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def exp(tensor: Tensor) -> Tensor: ...
def exp2(tensor: Tensor) -> Tensor: ...
def erf(tensor: Tensor) -> Tensor: ...
def floor(tensor: Tensor) -> Tensor: ...
def ge(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def gather(tensor: Tensor, indices: Tensor, axis: Any) -> Tensor: ...
def gt(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def le(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def relu(tensor: Tensor) -> Tensor: ...
def sigmoid(tensor: Tensor) -> Tensor: ...
def tanh(tensor: Tensor) -> Tensor: ...
def gelu(tensor: Tensor) -> Tensor: ...
def silu(tensor: Tensor) -> Tensor: ...
def softplus(tensor: Tensor) -> Tensor: ...
def elu(tensor: Tensor) -> Tensor: ...
def leaky_relu(tensor: Tensor) -> Tensor: ...
def logical_not(tensor: Tensor) -> Tensor: ...
def log(tensor: Tensor) -> Tensor: ...
def log2(tensor: Tensor) -> Tensor: ...
def lt(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def maximum(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def minimum(lhs: Tensor, rhs: Tensor) -> Tensor: ...
@overload
def mul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
@overload
def mul(lhs: Tensor, rhs: Any) -> Tensor: ...
@overload
def mul(lhs: Any, rhs: Tensor) -> Tensor: ...
def neg(tensor: Tensor) -> Tensor: ...
def ne(lhs: Tensor, rhs: Tensor) -> Tensor: ...
@overload
def pow(base: Tensor, exponent: Tensor) -> Tensor: ...
@overload
def pow(base: Tensor, exponent: Any) -> Tensor: ...
@overload
def pow(base: Any, exponent: Tensor) -> Tensor: ...
def recip(tensor: Tensor) -> Tensor: ...
def rsqrt(tensor: Tensor) -> Tensor: ...
def reduce_sum(
    tensor: Tensor,
    description: str,
    *,
    accumulator_dtype: SimpleDType | None = None,
) -> Tensor: ...
def reduce_prod(tensor: Tensor, description: str) -> Tensor: ...
def reduce_max(tensor: Tensor, description: str) -> Tensor: ...
def reduce_min(tensor: Tensor, description: str) -> Tensor: ...
def rem(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def reshape(tensor: Tensor, shape: Shape) -> Tensor: ...
def round(tensor: Tensor) -> Tensor: ...
def sign(tensor: Tensor) -> Tensor: ...
def sin(tensor: Tensor) -> Tensor: ...
def sqrt(tensor: Tensor) -> Tensor: ...
def cumsum(tensor: Tensor, dimension: Any) -> Tensor: ...
def conv_general(
    lhs: Tensor,
    kernel: Tensor,
    strides: Any,
    padding: Any,
    *,
    lhs_dilation: Any = None,
    kernel_dilation: Any = None,
    feature_groups: Any = 1,
    lhs_dims: Any = None,
    kernel_dims: Any = None,
    output_dims: Any = None,
) -> Tensor: ...

class SortResult(NamedTuple):
    values: Tensor
    indices: Tensor

def sort(tensor: Tensor, axis: Any = -1, descending: Any = False) -> SortResult: ...

class TopKResult(NamedTuple):
    values: Tensor
    indices: Tensor

def topk(tensor: Tensor, k: Any, axis: Any = -1, largest: Any = True) -> TopKResult: ...
def scatter(base: Tensor, indices: Tensor, updates: Tensor, axis: Any) -> Tensor: ...
def scatter_add(
    base: Tensor, indices: Tensor, updates: Tensor, axis: Any
) -> Tensor: ...
def select(condition: Tensor, on_true: Tensor, on_false: Tensor) -> Tensor: ...
def matmul(
    lhs: Tensor,
    rhs: Tensor,
    *,
    accumulator_dtype: SimpleDType | None = None,
) -> Tensor: ...
def move(tensor: Tensor, destination: Any) -> Tensor: ...
def einsum(lhs: Tensor, rhs: Tensor, description: str) -> Tensor: ...
@overload
def rearrange(tensor: Tensor, output: str) -> Tensor: ...
@overload
def rearrange(
    tensor: Tensor, output: Tree, selection: Tree | None = None
) -> Tensor: ...
def permute(tensor: Tensor, *order: Any) -> Tensor: ...
def squeeze(tensor: Tensor, dim: Any) -> Tensor: ...
def unsqueeze(tensor: Tensor, dim: Any) -> Tensor: ...
def profile(
    *,
    carriers: Iterable[type[Carrier]] | None = None,
    record_shapes: bool = False,
) -> Profiler: ...
