from contextlib import AbstractContextManager
from typing import Any, overload

from ._operation import Operation as Operation
from .layout import Tree
from .tensor import Tensor

__all__ = [
    "CpuToFileBackedMoveOperation",
    "ElementwiseMoveOperation",
    "EvictableOperation",
    "FileBackedToCpuMoveOperation",
    "GenericAddOperation",
    "GenericDivOperation",
    "GenericELUOperation",
    "GenericElementwiseMulOperation",
    "GenericExpOperation",
    "GenericGELUOperation",
    "GenericLeakyReLUOperation",
    "GenericMatmulOperation",
    "GenericPowOperation",
    "GenericReLUOperation",
    "GenericReduceSumOperation",
    "GenericScalarMulOperation",
    "GenericSiLUOperation",
    "GenericSigmoidOperation",
    "GenericSoftplusOperation",
    "GenericSubOperation",
    "GenericTanhOperation",
    "GenericViewOperation",
    "MoveOperation",
    "Operation",
    "PermuteOperation",
    "RearrangeOperation",
    "add",
    "div",
    "einsum",
    "elementwise_mul",
    "elu",
    "exp",
    "gelu",
    "is_grad_enabled",
    "leaky_relu",
    "matmul",
    "move",
    "mul",
    "neg",
    "no_grad",
    "permute",
    "pow",
    "rearrange",
    "reduce",
    "relu",
    "set_grad_enabled",
    "sigmoid",
    "silu",
    "softplus",
    "sub",
    "tanh",
    "view",
]

class GenericAddOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericSubOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericScalarMulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericElementwiseMulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericDivOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericExpOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericReLUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericSigmoidOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericTanhOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericGELUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericSiLUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericSoftplusOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericELUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericLeakyReLUOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericPowOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericReduceSumOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class GenericMatmulOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor, Tensor]: ...

class GenericViewOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class RearrangeOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class PermuteOperation(Operation):
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...

class MoveOperation(Operation):
    source_class: type | None
    destination_class: type | None
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor]: ...
    def _copy(
        self, tensor: Tensor, destination: Any, output: Tensor, element_count: int
    ) -> None: ...

class ElementwiseMoveOperation(MoveOperation): ...
class CpuToFileBackedMoveOperation(MoveOperation): ...
class FileBackedToCpuMoveOperation(MoveOperation): ...

class EvictableOperation(Operation):
    def __init__(self, primary_operation: Operation) -> None: ...
    @property
    def primary_operation(self) -> Operation: ...
    def _forward(self, *inputs: Any) -> Tensor: ...
    def forward(self, *inputs: Any) -> Tensor: ...
    def backward(self, gradient: Tensor) -> tuple[Tensor | None, ...]: ...

def is_grad_enabled() -> bool: ...
def set_grad_enabled(enabled: bool) -> None: ...
def no_grad() -> AbstractContextManager[None]: ...
def add(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def sub(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def neg(tensor: Tensor) -> Tensor: ...
def elementwise_mul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def mul(tensor: Tensor, scalar: Any) -> Tensor: ...
def div(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def exp(tensor: Tensor) -> Tensor: ...
def relu(tensor: Tensor) -> Tensor: ...
def sigmoid(tensor: Tensor) -> Tensor: ...
def tanh(tensor: Tensor) -> Tensor: ...
def gelu(tensor: Tensor) -> Tensor: ...
def silu(tensor: Tensor) -> Tensor: ...
def softplus(tensor: Tensor) -> Tensor: ...
def elu(tensor: Tensor) -> Tensor: ...
def leaky_relu(tensor: Tensor) -> Tensor: ...
def pow(tensor: Tensor, exponent: Any) -> Tensor: ...
@overload
def reduce(tensor: Tensor) -> Tensor: ...
@overload
def reduce(tensor: Tensor, description: str) -> Tensor: ...
def matmul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def move(tensor: Tensor, destination: Any) -> Tensor: ...
def einsum(lhs: Tensor, rhs: Tensor, description: str) -> Tensor: ...
@overload
def rearrange(tensor: Tensor, output: str) -> Tensor: ...
@overload
def rearrange(
    tensor: Tensor, output: Tree, selection: Tree | None = None
) -> Tensor: ...
def permute(tensor: Tensor, *order: Any) -> Tensor: ...
def view(tensor: Tensor, key: Any) -> Tensor: ...
